name: Build-pack-publishToNuget

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/RichLoggerProject/RichLogger/RichLogger.csproj
    - name: Creation du Nugget package
      run: dotnet pack ./src/RichLoggerProject/RichLogger/RichLogger.csproj --configuration Release -o NuGetPackages
    - name: Deploy NuGet Package
      run: dotnet nuget push ./src/RichLoggerProject/NuGetPackages/RichLogger.1.0.0.nupkg -k $ -s https://api.nuget.org/v3/index.json
